### PR TITLE
DEV-32193; chore: handle 429 http requests

### PR DESCRIPTION
**Pull request by loaiabdelhalim**

### CODE REVIEW

**Comment by abhijeetnarvekar** [comment]
@loaiabdelhalim

- Why `attemptCount` needs to class variable? Can it scope be reduced to `poll` function? I don't see it being used outside of the function.

- The `statusCode` state in Endpoint is ambiguous. Endpoint can run several checks in parallel.
   In case another check is initiated before last check result is processed, the status code might be holding value of latest 
   check and not the last check.

- Could you add tests?

**Review by abhijeetnarvekar — CHANGES_REQUESTED** [review]
@loaiabdelhalim

- Why `attemptCount` needs to class variable? Can it scope be reduced to `poll` function? I don't see it being used outside of the function.

- The `statusCode` state in Endpoint is ambiguous. Endpoint can run several checks in parallel.
   In case another check is initiated before last check result is processed, the status code might be holding value of latest 
   check and not the last check.

- Could you add tests?

**Comment by abhijeetnarvekar** [comment]
@loaiabdelhalim 429 is returned for check request, which is POST call. You have implemented it yourself here: https://github.com/acrolinx/sdk-php/blob/main/src/AcrolinxEndpoint.php#L194

Currently you seem to implement it for a GET request on polling. Does polling ever return a 429 at all?

The method `handlePotentialCancellation` is not correctly used. When platform returns 429, platform has not accepted your check request. There is no need of possible cancellation.

Please write tests

**Comment by pcdeshmukh** [comment]
wrong implementation

**Pull request closed without merging**
